### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-rust#31]
We need a proper manual, alike the one we have for the other SDKs: https://docs.restate.dev/

The idea is to have it in the rustdocs directly, so folks can explore it together with the API doc.

**Comment by slinkydeveloper** [comment]
FYI @gvdongen recording here what we discussed offline

**Comment by pstemporowski** [comment]
+1

**Comment by pstemporowski** [comment]
An advanced example would be incredibly helpful, as navigating Python/TypeScript tutorials and adapting them to the Rust SDK can be quite challenging.

**Comment by gvdongen** [comment]
@pstemporowski I'll make work of this today

**Comment by gvdongen** [comment]
@pstemporowski Here is a first example of multiple services: https://github.com/restatedev/examples/tree/main/tutorials/tour-of-restate-rust
I will rework this now to a Rust SDK tutorial but it should be enough to get you started with the main features.

**Comment by pstemporowski** [comment]
Oh that's really nice! Thanks

**Comment by gvdongen** [comment]
@pstemporowski We added Rust SDK docs as well now:  https://docs.rs/restate-sdk/latest/restate_sdk/
